//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.01 at 05:45:56 PM IST 
//


package com.mphrx.api._780;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mphrx.api._780 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mphrx.api._780
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DemographyRequest }
     * 
     */
    public DemographyRequest createDemographyRequest() {
        return new DemographyRequest();
    }

    /**
     * Create an instance of {@link DemographyResponse }
     * 
     */
    public DemographyResponse createDemographyResponse() {
        return new DemographyResponse();
    }

    /**
     * Create an instance of {@link Demographic }
     * 
     */
    public Demographic createDemographic() {
        return new Demographic();
    }

    /**
     * Create an instance of {@link PatientLoc }
     * 
     */
    public PatientLoc createPatientLoc() {
        return new PatientLoc();
    }

    /**
     * Create an instance of {@link Addr }
     * 
     */
    public Addr createAddr() {
        return new Addr();
    }

}
