//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.18 at 03:07:24 PM IST 
//


package com.mphrx.api.patientxsdpojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for demographic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="demographic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unidentifiablepatientReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="schooling" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profession" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="breed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "demographic", propOrder = {
    "unidentifiablepatientReason",
    "schooling",
    "profession",
    "breed"
})
public class Demographic {

    @XmlElement(required = true)
    protected String unidentifiablepatientReason;
    @XmlElement(required = true)
    protected String schooling;
    @XmlElement(required = true)
    protected String profession;
    @XmlElement(required = true)
    protected String breed;

    /**
     * Gets the value of the unidentifiablepatientReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnidentifiablepatientReason() {
        return unidentifiablepatientReason;
    }

    /**
     * Sets the value of the unidentifiablepatientReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnidentifiablepatientReason(String value) {
        this.unidentifiablepatientReason = value;
    }

    /**
     * Gets the value of the schooling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchooling() {
        return schooling;
    }

    /**
     * Sets the value of the schooling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchooling(String value) {
        this.schooling = value;
    }

    /**
     * Gets the value of the profession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfession() {
        return profession;
    }

    /**
     * Sets the value of the profession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfession(String value) {
        this.profession = value;
    }

    /**
     * Gets the value of the breed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreed() {
        return breed;
    }

    /**
     * Sets the value of the breed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreed(String value) {
        this.breed = value;
    }

}
