//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.18 at 03:07:24 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mphrx.com/api/PatientXSDPojo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mphrx.api.patientxsdpojo;
